Created template for MVT Profile data
NeighborhoodInfoDC/MVT pull request #2
Opened 2018-08-30 23:08 UTC by mcohenui

@ocarena This pull request contains the template.

2018-09-26 16:49 UTC, mcohenui commented
@ocarena So I am going to work on the Police, Prescat, and TANF/SNAP data separately. The next step for you is to write code to aggregate the tracts for the profile into two observations (47.01+47.02 and 47.01+47.02+106+46+48.02+49.02+58+59) using the compile_mvt_tabs_tr10 file. You won't need to do any aggregation for the city and ward indicators.

Once you have that, you will need to concatenate the different data sets so that you have one data set with an observation for each geography (Tract 47, Profile Area, Wards 6,7,8, and city-wide). Once you have done that, you can create any rates, percents, or ratios needed. Peter provided this program as a potential template for how to handle this step: L:\Libraries\Requests\Prog\2015\Anacostia_cltr_chars.sas. 

I will put some time on our calendars to talk through these steps.

2018-10-04 19:15 UTC, lhendey commented
@mcohenui - i'm getting errors in the log.

2018-10-04 19:25 UTC, lhendey commented on Prog/mt_vern_profile_data.sas
> +				births_total_2007 births_total_2008 births_total_2009 births_total_2010 births_total_2011
you also need births_w_race for a correct denominator if you are doing %.  need to suppress any counts 5 or less.

2018-10-04 19:35 UTC, lhendey commented on Prog/mt_vern_profile_data.sas
> +proc transpose data=compile_mvt_tabs out=mvt_tabs(label="Bridge Park Tabulations, &geo");
update label

2018-10-04 19:36 UTC, lhendey requested changes
@mcohenui - let me know when you resolve the errors in the log. I added a few comments but will review further when i can run the program.

2018-10-04 20:47 UTC, mcohenui commented
@lhendey  Tagging for review. Somehow managed to misspell your name on the original commit. Program should run cleanly now.

2018-10-04 21:54 UTC, lhendey requested changes
@mcohenui - i made some more comments. please batch submit the program before submitting for review. I'm still getting errors. I can't see the final data sets.

2018-10-04 21:54 UTC, lhendey commented on Prog/mt_vern_profile_data.sas
>  run;
@mcohenui should adjust for inflation first.

 %dollar_convert( originalvar, newvar, startyear, 2017, series=CUUR0000SA0L2 )

2018-10-04 21:54 UTC, lhendey commented on Prog/mt_vern_profile_data.sas
>  run;
also only use from 2002 forward....data before that are less accurate.

2018-10-04 21:54 UTC, lhendey commented on Prog/mt_vern_profile_data.sas
>  data compile_mvt_tabs_city;
this should not overwrite the existing temp file. put in a new name. (best practice).  also i'm getting missing values in the acs, tanf, data etc. on the compile_mvt_tabs_city file.

2018-10-04 21:54 UTC, lhendey commented on Prog/mt_vern_profile_data.sas
>  data compile_mvt_tabs_city;
should the project_&geosuf files get set in this statement too?

2018-10-04 21:54 UTC, lhendey commented on Prog/mt_vern_profile_data.sas
>  data compile_mvt_tabs_city;
it looks like there are several places where you are overwriting data sets -please review the whole program for this and correct.

2018-10-04 21:54 UTC, lhendey commented on Prog/mt_vern_profile_data.sas
>  	geography = Ward2012;
should specify a length statement for the geography var - its getting truncated for one of them.

2018-10-05 14:10 UTC, lhendey commented on Prog/mt_vern_profile_data.sas
>  run;
@mcohenui - you needed to put in saleyear not 2003 (otherwise you were treating all sales as if they were in 2003 dollars.)

2018-10-05 14:10 UTC, lhendey approved these changes

2018-10-05 14:11 UTC, lhendey commented
@mcohenui - you don't have all races accounted for - i'm assuming you want to get to 100%? look at the metadata - probably need multiple and native american.

crime rates should be per 1000 population. otherwise the format looks good.

2018-10-08 21:33 UTC, lhendey commented
@mcohenui  did you want me to try to do this now?

2018-10-08 21:42 UTC, mcohenui commented
@lhendey If you would have time to pull it together in the next hour or so. Otherwise, it can probably wait, I think.

2018-10-08 21:55 UTC, lhendey commented
@mcohenui - added to the "population"

2018-10-08 21:58 UTC, lhendey commented
@mcohenui made slight change to output - removed "estimate" for 2010 (based on July1) which differs slightly from Census 2010 (based on April 1).

2018-10-22 21:24 UTC, lhendey commented
@mcohenui - can you upload any other changes to this branch. let's merge it, close the issue and then @ocarena  and i can work from a new branch.

2018-10-22 21:33 UTC, merged